### ISSUE TITLE
Some of the command line options in Atril do not work

### ISSUE THREAD

**Issue by physicsshark** [mate-desktop/atril#138]
As described in [this thread](https://bbs.archlinux.org/viewtopic.php?id=199254), some of the command line options in Atril do not work.
--page-label, --page-index, --fullscreen, and --find all have problems.  I'm running 64-bit Arch Linux.
These issues are important because other programs should be able to run these functions in Atril.

**Comment by monsta** [comment]
Do they work in Evince (of which Atril is a fork)?

**Comment by monsta** [comment]
BTW, ```--fullscreen``` works for me in atril 1.10.1.

**Comment by monsta** [comment]
Fixed behavior of ```--find``` option in https://github.com/mate-desktop/atril/pull/154. Now the findbar is always shown when you use that option.

**Comment by physicsshark** [comment]
The `--fullscreen` option is now working for me too.  All of these options work in Evince.
As of atril 1.10.1, `--page-index` and `--page-label` still do not appear to work.

**Comment by monsta** [comment]
Yes, I confirm that about these two options.

**Comment by monsta** [comment]
I'm having problems making ```--page-label``` work even in Evince. Either I type the wrong labels, or my pdfs don't have any page labels at all. Do you have a sample document with labels which I could use for a test?

**Comment by physicsshark** [comment]
[Here's a pdf describing Google's Material design.](https://drive.google.com/file/d/0Bwy5oXKKSxdTdlRSSDlJRDBjVVU/view?usp=sharing)
Non-numeric page labels are uncommon, but with this pdf, `--page-label` worked as expected in Evince.

**Comment by monsta** [comment]
Thanks... but what are the label names there? :smile:

**Comment by monsta** [comment]
Ok, all command-line options are fixed now in https://github.com/mate-desktop/atril/pull/154.
